### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Generate One Time Withdraw QR Request
# @name generate_one_time_withdragenerateOneTimeWithdrawQRw_qr
POST {{host}}/withdraw_v1/generateOneTimeWithdrawQR
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{
  "Amount": 500,
  "OTPRegId": "{{OTPRegId}}",
  "OTPValue": "{{OTPValue}}",
  "CardNo": "0010101700633668",
  "NameOnCard": "name_on_card",
  "SecretKey": "2d290e496d16c9dcaa9b4ded5cac10cc",
  "AccountNo": "T-0063366",
  "UserName": "{{UserName}}",
  "ByUserId": 10,
  "UID": "{{ByUserId}}",
  "RolePermissionId": "6,1,1210",
  "PersonId": "{{PersonId}}",
  "EmployeeCode": "{{EmployeeCode}}",
  "MobileNo": "{{MobileNumber}}",
  "MobileNumber": "{{MobileNumber}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Response
# {
#     "Data": "$$MF@22A05A0533F4CA83F17E18E5090357",
#     "Status": "success",
#     "Message": null
# }