### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Get Loan Statement Request
# @name getLoanStatement
POST {{host}}/loans_v2/getLoanStatement
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
# {
#   "UserName": "{{UserName}}",
#   "UID": "{{ByUserId}}",
#   "ByUserId": "{{ByUserId}}",
#   "RolePermissionId": "6,1,1210",
#   "PersonId": "{{PersonId}}",
#   "EmployeeCode": "{{EmployeeCode}}",
#   "MobileNumber": "{{MobileNumber}}",
#   "MobileNo": "{{MobileNumber}}",
#  
#   "loanNo": "L004224",
#   "StartDate": "2023/7/1",
#   "EndDate": "2023-08-23T16:15:44+06:00"
# }

{
  "UserName":"shanta.ritchil@cccul.com",
  "UID":3428,
  "ByUserId":3428,
  "PersonId":60056,
  "EmployeeCode":"1093",
  "MobileNumber":"+880-1759494765",
  "MobileNo":"+880-1759494765",
  "RolePermissionId":" 108988",
  "loanNo":"L004224",
  "StartDate":"2023/7/1",
  "EndDate":"2023-09-03T16:30:34+06:00",
  "RequestFrom":"{{RequestFrom}}"
}

### Response
# {
#   "Data": [
#     {
#       "TxnDate": "2025-02-06T00:00:00",
#       "Particulars": "Opening BF",
#       "Balance": 0,
#       "LoanIssue": "100000.00",
#       "LoanRefundAmount": 0,
#       "InterestAmount": 0,
#       "LoanFine": 0,
#       "LPS": 0,
#       "LPSRF": 0,
#       "Deposit": 0,
#       "Withdrawal": 0,
#       "IssueDate": "0001-01-01T00:00:00",
#       "ExpiryDate": "0001-01-01T00:00:00",
#       "LoanId": "G20250121121226"
#     },
#     {
#       "TxnDate": "2025-02-06T00:00:00",
#       "Particulars": "JVDC202502060001/1 Transfer Loan Issue_Loan Number  G20250121121226",
#       "Balance": 100000,
#       "LoanIssue": "100000.00",
#       "LoanRefundAmount": 0,
#       "InterestAmount": 0,
#       "LoanFine": 0,
#       "LPS": 0,
#       "LPSRF": 0,
#       "Deposit": 100000,
#       "Withdrawal": 0,
#       "IssueDate": "0001-01-01T00:00:00",
#       "ExpiryDate": "0001-01-01T00:00:00",
#       "LoanId": "G20250121121226"
#     },
#     {
#       "TxnDate": "2025-05-12T00:00:00",
#       "Particulars": "JVDC202505120003/1 Transfer Loan Refinancing_Loan Number  G20250121121226",
#       "Balance": 210000,
#       "LoanIssue": "100000.00",
#       "LoanRefundAmount": 0,
#       "InterestAmount": 0,
#       "LoanFine": 0,
#       "LPS": 0,
#       "LPSRF": 0,
#       "Deposit": 110000,
#       "Withdrawal": 0,
#       "IssueDate": "0001-01-01T00:00:00",
#       "ExpiryDate": "0001-01-01T00:00:00",
#       "LoanId": "G20250121121226"
#     }
#   ],
#   "Status": "success",
#   "Message": null
# }