### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Submit Instant Loan Request
# @name submitLnstantLoan
POST {{host}}/loans_v2/submitInstantLoan
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{
  "UserName": "{{UserName}}",
  "UID": "{{ByUserId}}",
  "ByUserId": "{{ByUserId}}",
  "RolePermissionId": "6,1,1210",
  "PersonId": "{{PersonId}}",
  "EmployeeCode": "{{EmployeeCode}}",
  "MobileNumber": "{{MobileNumber}}",
  "MobileNo": "{{MobileNumber}}",
  "ModuleCode": "50",
  "NameOnCard": "BAPPY BESRA",
  "SecretKey": "1458e7509aa5f47ecfb92536e7dd1dc7",
  "CardNo": "0010102700635993",
  "AccountNo": "T-0063599",
  "AppliedAmount": 40000,
  "Amount": 0,
  "OTPRegId": "{{OTPRegId}}",
  "OTPValue": "{{OTPValue}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Response
# {
#     "Data": "Congratulations! your instant loan has been sanctioned and transferred to your savings account.",
#     "Status": "success",
#     "Message": null
# }