### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Reset Password
# @name resetPassword
POST {{host}}/securities_v1/forgotPassword
Content-Type: application/json
Accept: application/json


## Request Body
{
  "MobileNumber": "{{MobileNumber}}",
  "Password": "9efab2399c7c560b34de477b9aa0a465",
  "RequestFrom":"{{RequestFrom}}"
}

### Response
# {
#     "Data": "find_out",
#     "Status": "success",
#     "Message": null
# }