### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Forgot Password Request
# @name forgotPassword
POST {{host}}/securities_v1/forgotPassword
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{
  "ByUserId": "{{ByUserId}}",
  "DeviceRegId": "21687",
  "EmployeeCode": "{{EmployeeCode}}",
  "MobileNo": "{{MobileNumber}}",
  "MobileNumber": "{{MobileNumber}}",
  "Password": "{{EncryptedPassword}}",
  "PersonId": "{{PersonId}}",
  "RolePermissionId": "6,1,1210,1209",
  "UID": "{{ByUserId}}",
  "UserName": "{{UserName}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Response
# {
#     "Data": "find_out",
#     "Status": "success",
#     "Message": null
# }