name: pashboi
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  awesome_snackbar_content: ^0.1.5
  bloc: ^9.0.0
  connectivity_plus: ^6.1.3
  data_connection_checker_nulls: ^0.0.2
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flag: ^7.0.0
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  font_awesome_flutter: ^10.8.0
  animated_bottom_navigation_bar: ^1.4.0
  get_it: ^8.0.3
  intl: any
  jwt_decoder: ^2.0.1
  logger: ^2.5.0
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  uuid: ^4.5.1
  flutter_locales:
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  android_intent_plus: ^5.3.0
  url_launcher: ^6.3.1
  go_router: ^15.1.1
  dartz: ^0.10.1
  super_tooltip: ^2.0.9
  flutter_widget_from_html: ^0.16.0
  flutter_dotenv: ^5.2.1
  crypto: ^3.0.6
  circular_countdown_timer: ^0.2.4
  accordion: ^2.6.0
  progress_stepper: ^3.1.0
  syncfusion_flutter_charts: ^29.2.7
  image_picker: ^1.1.2
  flutter_html: ^3.0.0
  webview_flutter: ^4.4.1
  password_strength_indicator_plus: ^0.0.1
  r_nav_n_sheet: ^1.1.0
  pdf: ^3.11.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  external_path: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  floor_generator: ^1.5.0
  bloc_test:
  mocktail:

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/brand/
    - assets/images/bg/
    - assets/images/onboarding/
    - assets/images/misc/
    - assets/locales/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/RobotoBlack.ttf
          weight: 900
        - asset: assets/fonts/roboto/RobotoBold.ttf
          weight: 700
        - asset: assets/fonts/roboto/RobotoLight.ttf
          weight: 300
        - asset: assets/fonts/roboto/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/roboto/RobotoThin.ttf
          weight: 100
    - family: Sketch
      fonts:
        - asset: assets/fonts/sketch/Sketch.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/brand/company_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/brand/company_logo.png"
