### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


POST {{host}}/Deposit_bKash_V1/CreatebKashPayment/
Content-Type: application/json
Accept: application/json
Token: {{token}}

{
  "UserName": "newton.mitro@cccul.com",
  "UID": "21",
  "ByUserId": 21,
  "RolePermissionId": "6,1,1210",
  "PersonId": "63786",
  "EmployeeCode": "EmployeeCode",
  "MobileNumber": "+880-1704687376",
  "MobileNo": "+880-1704687376",
 
  "TransactionType": "bKashDepositRequest",
  "TotalDepositAmount": 10,
  "TransactionMethod": "11",
  "TransactionModels": [
    {
      "AccountNo": "0050726       ",
      "AccountType": "Share Account",
      "LedgerId": 1486,
      "Amount": 10,
      "Balance": 0,
      "AccountId": 226060,
      "AccountTypeCode": "10",
      "PlType": 1
    }
  ]
}