### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


POST {{host}}/Deposit_Bkash_V1/GetbKashPaymentServiceCharge
Content-Type: application/json
Accept: application/json
Token: {{token}}

{
  "UserName": "{{UserName}}",
  "AccountNo": "Not found.",
  "Gender": "M",
  "MobileNo": "{{MobileNumber}}",
  "MobileNumber": "{{MobileNumber}}",
  "RolePermissionId": "6,1,1209,1210",
  "ByUserId": "{{ByUserId}}",
  "UID": "{{ByUserId}}",
  "EmployeeCode": "{{EmployeeCode}}",
  "PersonId": "{{PersonId}}",
  "RequestFrom":"{{RequestFrom}}",
  "TotalAmount": 10
}