### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Apply For Card Issue Request
# @name applyForCardIssue
POST {{host}}/cards_V1/applyForCardIssue
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{
  "UserName": "{{UserName}}",
  "CardTypeCode": "01",
  "WithCard": true,
  "MobileNumber": "+880-1020202020",
  "RolePermissionId": "1,6,207,207,1209",
  "ByUserId": 5,
  "EmployeeCode": "{{EmployeeCode}}",
  "PersonId": 12345,
  "RequestFrom":"{{RequestFrom}}"
}

### Response
# {
#     "Data": "find_out",
#     "Status": "success",
#     "Message": null
# }