### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Verify Card PIN Request
# @name verifyCardPIN
POST {{host}}/cards_V1/verifyCardPIN
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{
  "UserName": "{{UserName}}",
  "CardNo": "{{CardNo}}",
  "AccountNo": "{{CardAccountNumber}}",
  "NameOnCard": "{{NameOnCard}}",
  "SecretKey": "81dc9bdb52d04dc20036dbd8313ed055",
  "MobileNumber": "{{MobileNumber}}",
  "RolePermissionId": "6,1,1210,1209",
  "ByUserId": "{{ByUserId}}",
  "EmployeeCode": "{{EmployeeCode}}",
  "PersonId": "{{PersonId}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Response
# {
#   "Data": {
#     "OTPRegId": "32513"
#   },
#   "Status": "success",
#   "Message": null
# }

