### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Submit Deposit Now Request
# @name submitDepositNow
POST {{host}}/MFSAPI/GetAGMAttendenceReport
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{
  "AccountNo": "",
  "Gender": "M",
  "IncludeSelf": false,
  "ByUserId": 2,
  "DeviceRegId": "16660",
  "EmployeeCode": "1226",
  "IMEI": "5b991844dc0b8968 - ab6121b6-b86a-4461-b6b9-b0aefe6e3b8f",
  "MobileNo": "+880-1686514521",
  "MobileNumber": "+880-1686514521",
  "PersonId": 52157,
  "RequestFrom": "MMS",
  "RequestTime": "Jan 13, 2024 4:40:05 PM",
  "RolePermissionId": " 54931",
  "UID": "2",
  "UserName": "anthony.gomes@cccul.com"
}

### Response
# {
#     "Data": "Your transaction has been completed successfully.",
#     "Status": "success",
#     "Message": null
# }