### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Get Durations Request
# @name getDurations
POST {{host}}/Accounts_V1/getDurations
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{
  "UserName": "{{UserName}}",
  "UID": "{{ByUserId}}",
  "ByUserId": "{{ByUserId}}",
  "RolePermissionId": "6,1,1210",
  "PersonId": "{{PersonId}}",
  "EmployeeCode": "{{EmployeeCode}}",
  "MobileNumber": "{{MobileNumber}}",
  "MobileNo": "{{MobileNumber}}",
  "ProductCode": "18",
  "RequestFrom":"{{RequestFrom}}"
}

### Response
# {
#   "Data": [
#     {
#       "DurationId": 2,
#       "DurationName": "5 Years",
#       "DurationInMonths": 60,
#       "InterestRate": 8.5
#     },
#     {
#       "DurationId": 3,
#       "DurationName": "10 Years",
#       "DurationInMonths": 120,
#       "InterestRate": 9
#     }
#   ],
#   "Status": "success",
#   "Message": null
# }