### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Get My Accounts Request
# @name getMyAccounts
POST {{host}}/accounts_V1/getMyAccounts
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{
  "UserName": "{{UserName}}",
  "UID": "{{ByUserId}}",
  "ByUserId": "{{ByUserId}}",
  "RolePermissionId": "6,1,1210",
  "PersonId": "{{PersonId}}",
  "EmployeeCode": "{{EmployeeCode}}",
  "MobileNumber": "{{MobileNumber}}",
  "MobileNo": "{{MobileNumber}}",
  "AccHolderPersonId": "3264",
  "RequestFrom":"{{RequestFrom}}"
}


#### Response
# {
#   "Data": [
#     {
#       "AccountNo": "T-0063599",
#       "DCAccountNo": "T-0063599",
#       "AccountTypeName": "Savings Account",
#       "AccountId": 59136,
#       "ledger_id": 1493,
#       "IsDefaulter": false,
#       "Balance": 186059,
#       "AccountTypeShortName": "SAV"
#       "MobileNumber": "",
#       "AccountFor": "Individual",
#       "HasOperator": false,
#       "AccountHolderInfoId": 123,
#     }
#   ],
#   "Status": "success",
#   "Message": null
# }
