### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Get Leave Policy Request
# @name getLeavePolicy
POST {{host}}/professionals_v1/getLeavePolicy
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{
  "ByUserId": 10,
  "EmployeeCode": "{{EmployeeCode}}",
  "MobileNo": "{{MobileNumber}}",
  "MobileNumber": "{{MobileNumber}}",
  "RolePermissionId": "6,1,1210,1209",
  "UID": "{{ByUserId}}",
  "UserName": "{{UserName}}",
  "personid": 12345,
  "RequestFrom":"{{RequestFrom}}"
}

### Response
# {
#     "Data": "find_out",
#     "Status": "success",
#     "Message": null
# }