### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Get Leave Histories Request
# @name getLeaveHistories
POST {{host}}/professionals_v1/getLeaveHistories
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{
  "UserName": "{{UserName}}",
  "UID": "{{ByUserId}}",
  "ByUserId": "{{ByUserId}}",
  "RolePermissionId": "6,1,1210",
  "PersonId": "{{PersonId}}",
  "EmployeeCode": "{{EmployeeCode}}",
  "MobileNumber": "{{MobileNumber}}",
  "MobileNo": "{{MobileNumber}}",
  "ToDate": "2023-08-24T12:59:04+06:00",
  "FromDate": "2022-08-01T00:00:00+06:00",
  "startRec": 0,
  "pageSize": 10,
  "searchText": "",
  "RequestFrom":"{{RequestFrom}}"
}

### Response
# {
#   "Data": [
#     {
#       "LeaveTypeCode": "03",
#       "LeaveType": "Hour Leave",
#       "LeaveApplicationId": 28,
#       "EmployeeId": 141,
#       "EmployeeName": "BAPPY BESRA",
#       "DepartmentName": "Information and Communication Technology Department",
#       "DesignationName": "Network Engineer",
#       "ApplicationDate": "2023-05-31T17:15:11",
#       "RejoiningDate": "2023-06-01T21:30:00",
#       "TotalLeaveDays": 0,
#       "Remarks": "",
#       "SupervisorName": "ANIMATIUS PANNA PERIS",
#       "FullName": "BAPPY BESRA",
#       "FallbackEmployeeCode": "1185",
#       "FallbackPersonId": 64025,
#       "FallbackPersonName": "BAPPY BESRA",
#       "CurrentStage": "Accepted By Fallback",
#       "StageCode": "02",
#       "FromDate": "2023-06-01T19:00:00",
#       "ToDate": "2023-06-01T21:30:00",
#       "PersonId": "{{PersonId}}",
#       "EmployeeCode": "1185"
#     }
#   ],
#   "Status": "success",
#   "Message": null
# }