### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Submit Payment Request
# @name submitPayment
POST {{host}}/payments_v2/submitPayment
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{
  "UserName": "{{UserName}}",
  "UID": "{{ByUserId}}",
  "ByUserId": "{{ByUserId}}",
  "RolePermissionId": "6,1,1210",
  "PersonId": "{{PersonId}}",
  "EmployeeCode": "{{EmployeeCode}}",
  "MobileNumber": "{{MobileNumber}}",
  "MobileNo": "{{MobileNumber}}",
  "AccHolder": "T-0063599", //card
  "AccNo": "T-0063599",  //card
  "AccTransfer": "T-0058497", //Receiver
  "AccType": "16",
  "AccountNo": "T-0063599", //card
  "AccountNumber": "T-0063599", //doesn't exist
  "Amount": 500,
  "CardNo": "0010102700635993",
  "SecretKey": "1458e7509aa5f47ecfb92536e7dd1dc7",
  "NameOnCard": "BAPPY BESRA",
  "Remarks": "3538",
  "OTPRegId": "{{OTPRegId}}",
  "OTPValue": "{{OTPValue}}",
  "RequestFrom":"{{RequestFrom}}",
  "PaymentServiceCode":"03",
  "NotifyPersonId":"20528"
}

### Response
# {
#     "Data": "Your transaction completed successfully with voucher no JVDC202308240001 and remaining balance 275409.00",
#     "Status": "success",
#     "Message": null
# }