### Login Request
# @name userLogin
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "newton.mitro@cccul.com",
  "Password": "9218c32cc68d2e1a4b151ffc87bc6e7c",
  "RequestFrom":"{{RequestFrom}}"
}

### Response:
# {
#   "Data": {
#     "AuthUserInfo": {
#       "UserId": 10,
#       "UserName": "NEWTON MITRA",
#       "UserPicture": "Base64",
#       "RoleIds": "6,1,1210,1209",
#       "RoleNames": "MFS User,Super Administrator,HRM Admin Web",
#       "RegisteredMobile": "{{MobileNumber}}",
#       "RegisteredEmail": "{{UserName}}",
#       "Address": "MIRPUR,KAFRUL,DHAKA",
#       "OrganizationCode": "001",
#       "BranchCode": "00 ,00 ,00 ",
#       "PersonId": "{{PersonId}}",
#       "EmployeeCode": "{{EmployeeCode}}",
#       "DeviceId": 16554
#     },
#     "PassbookMenus": [
#       {
#         "MenuId": 446,
#         "ParentMenuId": 0,
#         "MenuName": "MFS App Menu",
#         "Icon": "",
#         "Sort": 19,
#         "RolePermissionIds": "",
#         "MfsIcon": "Base64"
#       }
#     ],
#     "WebPortalMenus": [
#       {
#         "MenuId": 446,
#         "ParentMenuId": 0,
#         "MenuName": "MFS App Menu",
#         "Icon": "",
#         "Sort": 19,
#         "RolePermissionIds": "",
#         "MfsIcon": "Base64"
#       }
#     ]
#   },
#   "Status": "success",
#   "Message": null
# }

