### Login Request
# @name login
POST  {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Get Profile Request
# @name get_profile
POST {{host}}/info_V1/getUserProfile
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{
  "UserName": "{{UserName}}",
  "AccountNo": "Not found.",
  "Gender": "M",
  "MobileNo": "{{MobileNumber}}",
  "MobileNumber": "{{MobileNumber}}",
  "RolePermissionId": "6,1,1209,1210",
  "ByUserId": "{{ByUserId}}",
  "UID": "{{ByUserId}}",
  "EmployeeCode": "{{EmployeeCode}}",
  "PersonId": "{{PersonId}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Response
# {
#   "Data": [
#     {
#       "FullName": "SUJON DOMINIC GOMES",
#       "FathersName": "LATE. CHRISTOPHER GOMES",
#       "MothersName": "MRS. SABITA JACINTA GOMES",
#       "SpouseName": "MRS. SILVIA ANTHONIA CORRAYA",
#       "DateOfBirth": "1984-11-01T00:00:00",
#       "MobileNumber": "+880-1716281408",
#       "Email": "sujon_gomes2004@yahoo.com",
#       "NID": "3313497650235",
#       "BaseNo": "0013815",
#       "PresentAddressLine1": "70/1/A",
#       "PresentAddressLine2": "1215",
#       "PresentAddressLine3": "TEJGAON",
#       "PresentAddressLine4": "DHAKA",
#       "PermanentAddressLine1": "RANGAMATIA",
#       "PermanentAddressLine2": "1720",
#       "PermanentAddressLine3": "KALIGANJ",
#       "PermanentAddressLine4": "GAZIPUR",
#       "DeviceId": 29365,
#       "UserPhoto": "",
#       "IsBloodDonor": true,
#       "BloodGroup": "O (+)"
#     }
#   ]
# }